version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.6
    volumes:
      - postgres_data:/var/lib/postresql/data/
    environment:
      - POSTGRES_USER=webApp
      - POSTGRES_PASSWORD=webApp
      - POSTGRES_DB=webApp_dev

volumes:
  postgres_data: